[[main]]
name = "Blog"
pageRef = "posts"
weight = 1

[[main]]
name = "About"
pageRef = "about"
weight = 2

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/solumath/"
  weight = 3
